; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir=ESP_ATMod

[env:esp01_1m]
platform = espressif8266
board = esp01_1m
framework = arduino

board_build.flash_mode = dout

[env:esp8266_atmod]
platform      = espressif8266
board         = esp_wroom_02
framework     = arduino

upload_speed  = 115200
monitor_speed = 115200

board_build.flash_mode = dio
board_build.f_flash    = 40000000L
board_build.flash_size = 2MB

build_flags =
    -DPIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
    -DATMOD_SSL_SUPPORT
    -DATMOD_TLS1_2